enum
{
    alpha,
    beta,
    gamma,
    delta,
    epsilon,
    zeta,
    eta,
    theta,
    iota,
    kappa,
    lambda,
    mu,
    nu,
    xi,
    omicron,
    pi,
    rho,
    sigma,
    tau,
    upsilon,
    phi,
    chi,
    psi,
    omega
};

int rotation_table[24][24] = {
    {alpha, beta, gamma, delta, epsilon, zeta, eta, theta, iota, kappa, lambda, mu, nu, xi, omicron, pi, rho, sigma, tau, upsilon, phi, chi, psi, omega},
    {beta, alpha, delta, gamma, theta, chi, omega, epsilon, phi, psi, pi, omicron, sigma, rho, mu, lambda, xi, nu, upsilon, tau, iota, zeta, kappa, eta},
    {gamma, delta, alpha, beta, tau, iota, psi, upsilon, zeta, omega, mu, lambda, rho, sigma, pi, omicron, nu, xi, epsilon, theta, chi, phi, eta, kappa},
    {delta, gamma, beta, alpha, upsilon, phi, kappa, tau, chi, eta, omicron, pi, xi, nu, lambda, mu, sigma, rho, theta, epsilon, zeta, iota, omega, psi},
    {epsilon, theta, upsilon, tau, beta, xi, lambda, alpha, nu, mu, omega, psi, phi, chi, kappa, eta, zeta, iota, gamma, delta, sigma, rho, omicron, pi},
    {zeta, phi, iota, chi, lambda, gamma, rho, omicron, alpha, xi, tau, epsilon, eta, omega, upsilon, theta, psi, kappa, mu, pi, delta, beta, nu, sigma},
    {eta, psi, omega, kappa, nu, lambda, delta, rho, pi, alpha, phi, iota, upsilon, epsilon, zeta, chi, tau, theta, sigma, xi, omicron, mu, gamma, beta},
    {theta, epsilon, tau, upsilon, alpha, rho, pi, beta, sigma, omicron, eta, kappa, iota, zeta, psi, omega, chi, phi, delta, gamma, nu, xi, mu, lambda},
    {iota, chi, zeta, phi, mu, alpha, nu, pi, gamma, sigma, epsilon, tau, psi, kappa, theta, upsilon, eta, omega, lambda, omicron, beta, delta, rho, xi},
    {kappa, omega, psi, eta, xi, omicron, alpha, sigma, mu, delta, zeta, chi, epsilon, upsilon, phi, iota, theta, tau, rho, nu, lambda, pi, beta, gamma},
    {lambda, omicron, pi, mu, phi, omega, tau, zeta, eta, epsilon, sigma, nu, delta, beta, xi, rho, gamma, alpha, iota, chi, kappa, psi, upsilon, theta},
    {mu, pi, omicron, lambda, chi, kappa, epsilon, iota, psi, tau, xi, rho, beta, delta, sigma, nu, alpha, gamma, zeta, phi, omega, eta, theta, upsilon},
    {nu, rho, xi, sigma, psi, epsilon, phi, eta, upsilon, iota, beta, gamma, omicron, mu, alpha, delta, lambda, pi, omega, kappa, theta, tau, zeta, chi},
    {xi, sigma, nu, rho, omega, upsilon, zeta, kappa, epsilon, chi, gamma, beta, lambda, pi, delta, alpha, omicron, mu, psi, eta, tau, theta, phi, iota},
    {omicron, lambda, mu, pi, zeta, psi, theta, phi, kappa, upsilon, rho, xi, alpha, gamma, nu, sigma, beta, delta, chi, iota, eta, omega, epsilon, tau},
    {pi, mu, lambda, omicron, iota, eta, upsilon, chi, omega, theta, nu, sigma, gamma, alpha, rho, xi, delta, beta, phi, zeta, psi, kappa, tau, epsilon},
    {rho, nu, sigma, xi, eta, tau, chi, psi, theta, zeta, delta, alpha, pi, lambda, gamma, beta, mu, omicron, kappa, omega, upsilon, epsilon, iota, phi},
    {sigma, xi, rho, nu, kappa, theta, iota, omega, tau, phi, alpha, delta, mu, omicron, beta, gamma, pi, lambda, eta, psi, epsilon, upsilon, chi, zeta},
    {tau, upsilon, theta, epsilon, delta, sigma, mu, gamma, rho, lambda, kappa, eta, chi, phi, omega, psi, iota, zeta, alpha, beta, xi, nu, pi, omicron},
    {upsilon, tau, epsilon, theta, gamma, nu, omicron, delta, xi, pi, psi, omega, zeta, iota, eta, kappa, phi, chi, beta, alpha, rho, sigma, lambda, mu},
    {phi, zeta, chi, iota, omicron, beta, sigma, lambda, delta, nu, theta, upsilon, kappa, psi, epsilon, tau, omega, eta, pi, mu, alpha, gamma, xi, rho},
    {chi, iota, phi, zeta, pi, delta, xi, mu, beta, rho, upsilon, theta, omega, eta, tau, epsilon, kappa, psi, omicron, lambda, gamma, alpha, sigma, nu},
    {psi, eta, kappa, omega, rho, mu, beta, nu, omicron, gamma, chi, zeta, theta, tau, iota, phi, epsilon, upsilon, xi, sigma, pi, lambda, alpha, delta},
    {omega, kappa, eta, psi, sigma, pi, gamma, xi, lambda, beta, iota, phi, tau, theta, chi, zeta, upsilon, epsilon, nu, rho, mu, omicron, delta, alpha}};